#!/bin/sh
set -e
# postinst script 
# see: dh_installdeb(1)
#DEBHELPER#

case "$1" in
	configure)
	systemctl enable nvwa.service
	systemctl enable nvwa-pre.service
	systemctl start nvwa.service
	;;
	*)
        exit 1
        ;;
esac

exit 0
